### ISSUE TITLE
Stop scanning inside success callback

### ISSUE THREAD

**Issue by MikeG1983** [nimiq/qr-scanner#100]
It seems like it would be a common requirements to stop scanning once a QR code is found. However, due to the way the library is written it doesn't seem that this is possible. You cannot call stop() inside the success callback because the QrScanner instance has not yet been created. For example:

```
const qrScanner = new QrScanner(videoElem, () => {
    alert('decoded QR code: ' + result);
    // How can we stop the QR scanner here? 
});
```

Does anyone know how you can stop scanning inside the success callback?

**Comment by sisou** [comment]
AFAIK you can simply use the `qrScanner` variable you assigned. At the time of the callback execution, it is defined and refers to the scanner instance.

**Comment by MikeG1983** [comment]
Thanks for your reply sisou. How would I reference it? When the variable doesn't yet exist?

**Comment by sisou** [comment]
It _is_ defined. You can just use it:

```js
const qrScanner = new QrScanner(videoElem, () => {
    alert('decoded QR code: ' + result);
    qrScanner.stop();
});
```

**Comment by MikeG1983** [comment]
Thank you sisou. My knowledge of JavaScript is not the best! I will give this a try and close the issue if it works.
