### ISSUE TITLE
On ios, iPad, iPhone frequent RangeError: Array size is not a small enough positive integer at line 23:293

### ISSUE THREAD

**Issue by ryanreid22** [nimiq/qr-scanner#102]

**Comment by sisou** [comment]
According to the line and character number `23:293`, this error is attributed to a `.map()` call in `qr-scanner-worker.min.js`:

```
.map((a,b,c)=>{if(4<b)return null;c=c.filter((a,c)=>b!==c).map(b=>({x:b.x,y:b.y,score:b.score+Math.pow(b.size-a.size,2)/a.size,size:b.size})).sort((a,b)=>a.score-b.score);if(2>c.length)return null;const d=a.score+
c[0].score+c[1].score;return{points:[a].concat(c.slice(0,2)),score:d}})
```
which, formatted, is this:
```js
        .map((a, b, c) => {
            if (4 < b) return null;

            c = c.filter((a, c) => b !== c)
                .map(b => ({
                    x: b.x,
                    y: b.y,
                    score: b.score + Math.pow(b.size - a.size, 2) / a.size,
                    size: b.size,
                }))
                .sort((a, b) => a.score - b.score);
            
            if (2 > c.length) return null;
            
            const d = a.score + c[0].score + c[1].score;
            return {
                points: [a].concat(c.slice(0, 2)),
                score: d,
            };
        })
```

**Comment by Mr-Rayman** [comment]
I can confirm this error! Performance on Android devices is very good, however on iPhone 8 I see this RangeError Array size often and the detection performance is very poor, e.g. it takes very long to detect a QR code, or QR codes are not detected at all, even if light and camera focus is perfect.

**Comment by emielergo** [comment]
Hi All,

I too can confirm this issue. Has anyone found a solution or workaround? Or is this unsolvable?

**Comment by sisou** [comment]
As this library is ultimately based on cozmo/jsQR, this issue in their repository is relevant:
https://github.com/cozmo/jsQR/issues/157

It says that it happens in iOS 13/14 under some circumstances, but no solution is available yet, except ignoring the error with a try...catch.

**Comment by Antibreez** [comment]
@sisou Can you please show example with solution with try...catch

**Comment by MrAntix** [comment]
Its not intermittent for me on iOS 14.5 happens every time

@sisou is the try catch for us to implement somewhere or needed in the lib?

**Comment by walva** [comment]
I have the same error. I have no clue at this point how to solve it.

**Comment by danimoh** [comment]
I implemented a fix which should hopefully mitigate this.
However, as I don't own an iPhone, I unfortunately can't confirm this myself.
Please test the latest release and let me know whether you still encounter this issue.

**Comment by danimoh** [comment]
As no more reports were posted, I believe the fix worked.
