### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by MrCircuit** [nimiq/qr-scanner#104]
Hi,

When checking the flash capability, the following warning is displayed:

"TypeError: Cannot read property 'includes' of undefined at qr-scanner.js:81"

Could this be fixed by checking for the existance of "fillLightMode" before accessing its member?
https://github.com/nimiq/qr-scanner/blob/e8a77dea3fd5e1d7f403779bd95ff827b835baff/src/qr-scanner.js#L81

Best regards
Uwe

**Comment by danimoh** [comment]
Hello Uwe.
Yes, we could have checked for it ;)
But this was just a console warning, the exception was handled correctly.
However, the latest implementation now uses a different approach for detecting the flash anyways.
