### ISSUE TITLE
QR-Scanner & Demo crashes Android Browsers

### ISSUE THREAD

**Issue by Mr-Rayman** [nimiq/qr-scanner#105]
I can reproduce this behavior very often on my Android Tablet Samsung Galaxy S5e or Galaxy S7 phone when using this Javascript in my own application and even with just the plain demo-version here on github. I see this in stock "Samsung Internet Browser" as well as Google Chrome.

Steps to reproduce:

1) Just turn scanning on with Show Scan-Region enabled
2) Leave the device as is, do not scan any QR codes
3) After 1-2 minutes the browser window will freeze and turn black and the browser crashes - see photos attached
4) After a while the browser will restore itself, loading the demo page again - starting this process again at Step 2

![GitHub_Demo](https://user-images.githubusercontent.com/54250320/107848305-b02a2f80-6df2-11eb-98a2-7ce03c32f2bf.jpg)

![CrashAfter80sec](https://user-images.githubusercontent.com/54250320/107848306-b1f3f300-6df2-11eb-8635-dc80d6134aab.jpg)

**Comment by danimoh** [comment]
Hum, are you using the latest version of Chrome?
I couldn't reproduce this, even on an older phone and running it for a couple of minutes.

**Comment by SimonCollings** [comment]
I can reproduce this on a Galaxy a72 phone (scanning area goes black) and Galaxy 10.1 Tablet (scanning area just freezes).

**Comment by danimoh** [comment]
What browser and browser version are you experiencing this with?

**Comment by Mr-Rayman** [comment]
I've just tested the recent demo version on my Android Tablet and did not see any crashes. So I would close this ticket for the moment. Thank your for your development!
