### ISSUE TITLE
how to change rear cam to front cam

### ISSUE THREAD

**Issue by ruzlicali16** [nimiq/qr-scanner#106]
How can i change it when i build my project and run it into phone then it always shows reart cam. how can i change rear cam default into front cam. Please help. I'm stucked here!

**Comment by Mr-Rayman** [comment]
See the github documentation > Usage > 2. Create a QrScanner Instance

`const qrScanner = new QrScanner(videoElem, result => console.log('decoded qr code:', result));`

"As an optional fifth parameter a preference for the camera to use can be specified. Allowed values are 'environment' and 'user'. The default is 'environment'.

Change the fifth parameter in `new QrScanner` to '`user`' to get the front cam.

**Comment by ruzlicali16** [comment]
const qrScanner = new QrScanner(videoElem, result => console.log('decoded qr code:', result), 'user');

Like this?

**Comment by stjjelic** [comment]
const qrScanner = new QrScanner(video, result => dotNetObject.invokeMethodAsync('GetByIdFromScan', result), QrScanner._onDecodeError, undefined, 'user');
Like this for front camera.

**Comment by mhosman** [comment]
Not working even adding the 'user' option. Flash also not being detected. This repo is still alive?

**Comment by danimoh** [comment]
Please check the latest release.
Regarding the flash: this is generally only supported in Chromium based browsers and camera specific, e.g. typically the rear camera has a flash but the user facing camera not.
