### ISSUE TITLE
canvasSizeOrCalculateScanRegion is type number - how can it hold 6 values?

### ISSUE THREAD

**Issue by louis123562** [nimiq/qr-scanner#108]
Hello,

as far as i can see, the `canvasSizeOrCalculateScanRegion` ist of type `number`.

In the ReadMe, there is written, that it should hold up to six values.

How can i store six values in a single number Object?!

**Comment by louis123562** [comment]
Can you explain how i can set canvasSizeOrCalculateScanRegion ?
Is it also possible to cut the video?

**Comment by ZNS** [comment]
If you got the code from NPM it's an older version of the code.

**Comment by danimoh** [comment]
A new version has been published now, with a couple of additional improvements :)
