### ISSUE TITLE
is there any way to get the coordinates of qrcode to draw a box around it?

### ISSUE THREAD

**Issue by adityar15** [nimiq/qr-scanner#109]

**Comment by danimoh** [comment]
Not yet, but it's a nice feature suggestion.
I hope I'll get to working on this in the near future.

**Comment by samuelcolvin** [comment]
this would be great, any idea when it might land?

**Comment by danimoh** [comment]
Just landed! :)
You can now get both, the coordinates of the corners for custom processing and the outline of the code automatically rendered on screen.
The rendered outline can be easily styled via css.
Have a look at the readme and demo for examples..
