### ISSUE TITLE
problem with chrome mobile android i get "Worker error"

### ISSUE THREAD

**Issue by fdamore-xnoova** [nimiq/qr-scanner#11]
if i scan a qrcode from file with the demo using chrome with an android mobile i get "Worker error" instead of the qrcode value. It works fine with Chrome Desktop MacOs

**Comment by danimoh** [comment]
Hello,
This is now documented in the readme.
Sorry for the confusion.

**Comment by abidhkm** [comment]
I am getting the same error even if I modified the qr-scanner.min.js

**Comment by abidhkm** [comment]
should i use qr-scanner.min.js or qr-scanner.js ? in both i'm getting error
