### ISSUE TITLE
Checksums?

### ISSUE THREAD

**Issue by uncovery** [nimiq/qr-scanner#119]
Hi, I tried another JS QR code library and that would sometimes return faulty text (one letter different etc), so I wanted to know if this one has a checksum functionality included or not.

thanks!.

**Comment by danimoh** [comment]
See https://github.com/cozmo/jsQR/issues/212:

> QR codes include additional data for error correction. The error correction level can be configured when creating a qr code.
Higher error correction capabilities come at the cost of larger QR codes / more dense QR codes which might be harder to read.
So there's a sweet spot.
But that just as a sidenote.
>
> Yes, this project makes use of the error correction feature and generally works pretty well.
In case you've been trying [LazarSoft/jsqrcode](https://github.com/LazarSoft/jsqrcode) (another popular lib): from my testing and diving into the code, that lib is a rather poor implementation.
See [here for a benchmark and alternatives](https://github.com/danimoh/qr-scanner-benchmark).

(Note that this project uses an improved fork of cozmo/jsQR)

**Comment by uncovery** [comment]
Thanks for the reply, I was not aware these two are connected.

**Comment by danimoh** [comment]
FYI: a new version was just published with some improvements :)

**Comment by uncovery** [comment]
Sorry for the lat reply, thanks for the update!
