### ISSUE TITLE
Uncaught (in promise) Camera not found.

### ISSUE THREAD

**Issue by aunghtet-star** [nimiq/qr-scanner#123]
Why happen this error. My local server has normally working but I am hosting ,I have this error.

**Comment by sisou** [comment]
Hi. Please share more of your system. Are you hosting on `localhost`? Do you want to access a laptop camera, or a phone camera? Which browser on which operating system are you using?

**Comment by sisou** [comment]
Cameras can also only be accessed when the page is served securely via HTTPS. If it's not secure, camera cannot be accessed on your hosting.

**Comment by danimoh** [comment]
Hello @aunghtet-star.
Please check whether the developer tools console shows the warning `The camera stream is only accessible if the page is transferred via https` for your hosted website (make sure that errors of reporting level "warnings" are enabled).
If so, you need to serve your website via https.

Also make sure, that you didn't block camera access for the website in your browser.
You can check your browser's site settings for your website or the address bar for whether camera access is enabled.

**Comment by danimoh** [comment]
Closing this as I believe all relevant information for this issue has been stated.
