### ISSUE TITLE
destroy should stop

### ISSUE THREAD

**Issue by pstanton** [nimiq/qr-scanner#127]
qr-scanner@^1.3.0:
version "1.3.0"

If you destroy a "started" instance, it should automatically "stop" it. Currently the "camera in use" message persists if you destroy without stopping first.

**Comment by danimoh** [comment]
Hum, started instances are already being stopped on destroy, see https://github.com/nimiq/qr-scanner/blob/8bb46c3cbc6e6b1c256a7ef6abc866d734493f36/src/qr-scanner.ts#L328-L338

However, in your case there might have been a race condition where `qrScanner.start()` only finished after `qrScanner.destroy()` was already called.
This has been fixed now, see #90.
Please check whether this solved your issue.
If it didn't, please reopen.
