### ISSUE TITLE
Worker error in firefox.

### ISSUE THREAD

**Issue by SMYEE** [nimiq/qr-scanner#13]
i got 'worker error' in firefox when show debug image checkbox is checked. please help.

**Comment by SMYEE** [comment]
i found that i put wrong file path in qr-scanner.min.js. Then, i put right path and worker error is solved. QrScanner.WORKER_PATH="../Scripts/App/QRScan/qr-scanner-worker.min.js"; :)

**Comment by danimoh** [comment]
For anyone struggling with this:
The api has been simplified now.
Specifying the WORKER_PATH is not required anymore in the newest release, have a look at the readme :)
