### ISSUE TITLE
>No support for turn on Torchlight on ios

### ISSUE THREAD

**Issue by Lorill28** [nimiq/qr-scanner#131]
After have done several tests, it is not possible at all to turn on the flashlight on iOS.
I tried on iphone 5 SE and Iphone 6 but whith no success.
Is there any solution out there ?
Which iphone model support this feature ( => scanner.turnFlashOn() )?

Is there a workaround for this issue?

Any tip or piece of code to suggest ?

**Comment by Lorill28** [comment]
Yes indeed ! What a pity !
According to my research there is no way to turn on the torchlight on iOS devices.
=> In Safari 14 there is no support at all to the "ImageCapture" API and there are lacks to the "getUserMedia" API (for i.e. : no supported option in "Constraints" to apply torch : true).
And it's the same for other browsers on iOS since they use the same routine limit as Safari !

No way, I give up !
Too bad Apple !

**Comment by clawfire** [comment]
Well. The good thing is, you can use it here and implement a feature detection with `hasTorch()` and provide better experience for users who already have it, and be ready for when Apple will support it 😃

**Comment by danimoh** [comment]
Yes, unfortunately Apple has not implemented this feature.
But once (and if) they do, it will automatically start working.
