### ISSUE TITLE
DOMException: The play() request was interrupted by a new load request.

### ISSUE THREAD

**Issue by anliting** [nimiq/qr-scanner#139]
I think the following code should not produce any error, while it does:
```
let qrScanner=new QrScanner(document.createElement('video'),()=>{})
for(let i=0;i<100;i++){
    qrScanner.start()
    qrScanner.stop()
}
```

It gives several error: "Uncaught (in promise) DOMException: The play() request was interrupted by a new load request."

I guess it is a bug and it is related to this: https://developers.google.com/web/updates/2017/06/play-request-was-interrupted

I am not intended to run `qrScanner.start();qrScanner.stop()` 100 times. It is just a minimal example to illustrate the problem.

**Comment by danimoh** [comment]
Hello, your linked article states that `video.pause()` should only be called when `video.play()` resolved.
In the same fashion, you should `await` `qrScanner.start()` and `qrScanner.stop()`.
To make this a bit more resilient, internal calls to `video.play()` are now awaited.
Thanks for the hint.
