### ISSUE TITLE
SetTimeout not working when a QR is found

### ISSUE THREAD

**Issue by cabesd** [nimiq/qr-scanner#14]
Hi there,
I'm trying to find a solution for this but can't find where the problem is originated in the qr-scanner.js file.

When a QR code is found, the resulting function is being executed multiple times.
You can test it by just changing the demo's function as follow (I'm just adding an alert call)

`    function setResult(label, result) {
        alert('setResult');
        label.textContent = result;
        label.style.color = 'teal';
        clearTimeout(label.highlightTimeout);
        label.highlightTimeout = setTimeout(() => label.style.color = 'inherit', 100);
    }`

And you'll see that the alert is executed multiple times.

**Comment by jjarpa** [comment]
Hi Cabesd.
    i'm facing the same problem, my QRcodes are read multiple times....Did you find some workaround?

BR.

Jose.

**Comment by masterdany88** [comment]
Me too

**Comment by danimoh** [comment]
Hello.
The qr scanner continuously scans the camera stream for qr codes. It doesn't stop after a qr code has been found.
If that's the behavior you want, you have to `stop()` the scanner manually or implement your `onDecode` callback in such a way that it ignores subsequent scan results.
