### ISSUE TITLE
"Scanner error: timeout" in Safari (MacOS and iOS) after destroying and re-initializing

### ISSUE THREAD

**Issue by dr-erych** [nimiq/qr-scanner#144]
Thank you for your great and easy-to-use QR scanner library.

I came across a bug when using qr-scanner in a vue3 component and succeeded to reproduce the problem in a Codepen (without vue): https://codepen.io/dr_erych/pen/NWwjpyg

* When mounting the scanner, I instantiate QrScanner and call start() on the instance:  
```js
  async startScanner() {    
    this.qrScanner = new QrScanner(this.elVideo, (result) => {
      this.elInput.value = result;
      this.stopScanner();
    });
    await this.qrScanner.start();
  }
```
* When unmounting the scanner (user clicking a button or as soon as a QR code is detected), I call stop() on the instance and afterwards destroy()
```js
  async stopScanner() {    
    await this.qrScanner.stop();
    this.qrScanner.destroy(); // removing this line solves the issue
  }
```

This works fine in Chrome and Firefox but in Safari on my Mac or iPhone I can only successfully start the scanner _once_. After destroying, the newly instantiated scanner will not successfully start anymore but after 10000ms the message `Scanner error: timeout` is logged to the console.

My current solution is to just not `destroy()` the scanner but only `stop()` it, but probably it's worth looking into it and fixing it.

**Comment by danimoh** [comment]
Hello, this behavior is intended.
A destroyed scanner instance can not be used anymore, as the `destroy()` call performs some clean up and leaves the scanner dysfunctional.
If you intend to restart the scanner, not destroying it is the correct usage.
I now made the documentation a little clearer about this.

**Comment by matthieu-beteille** [comment]
yea that part makes sense - the problem was that if you ever wanted to create a new scanner after having destroyed one before it wouldn't work (at least on safari).

but this has now fixed it: https://github.com/nimiq/qr-scanner/commit/93732377187d5161ab0354f5b9e906c819ccbc26
