### ISSUE TITLE
QrScanner namespace types are not exported anymore

### ISSUE THREAD

**Issue by cmxl** [nimiq/qr-scanner#147]
Since version 1.4.0 the `export`s have been removed from all types in the namespace `QrScanner`.
see types here: https://github.com/nimiq/qr-scanner/blob/8bb46c3cbc6e6b1c256a7ef6abc866d734493f36/types/qr-scanner.d.ts#L88

**Comment by sebastianrothe** [comment]
I am missing the type `ScanResult`, too.

**Comment by danimoh** [comment]
Thanks, guys.
This is now fixed in version 1.4.1 :+1:
