### ISSUE TITLE
Syntax error: expected expression, got '<'

### ISSUE THREAD

**Issue by phorward** [nimiq/qr-scanner#15]

**Comment by phorward** [comment]
Hi!

I'm getting this error now, both in Firefox 62 and Chromium 69. I've checked out the latest version of qr-scanner from the git repo and used the files provided there, but still get this error.

The problem only occurs when creating a new element, which I do with

```javascript
new window.top.qrScanner(window.top.document.getElementById('qr-video'), result => console.log('decoded qr code:', result))
```

Here's the output of the JavaScript consoles in both browsers:
![image](https://user-images.githubusercontent.com/16870072/47779787-3ee61180-dcfa-11e8-9f53-87ffd269f53a.png)

Any quick solution for that?

**Comment by phorward** [comment]
yay, #11 did the trick!

**Comment by phorward** [comment]
Hi @abidhkm, have you changed the path as advised in #11?
Since I've done this, the library runs perfectly.

**Comment by abidhkm** [comment]
yes..
should i use qr-scanner.min.js or qr-scanner.js ?
