### ISSUE TITLE
Importing main script requires script in non-existing folder

### ISSUE THREAD

**Issue by andrewebdev** [nimiq/qr-scanner#16]
When I import `import QrScanner from 'qr-scanner/qr-scanner.min.js';`

In one of my modules I get a 404 when that script is imported cause it's trying to import the worker script from a non-existent `libraries` folder.

`https://webapp.localhost/libraries/qr-scanner/qr-scanner-worker.min.js`

It should not have paths hardcoded and should be using bare module imports

**Comment by shershen08** [comment]
If you're using webpack as a build tool you might use https://github.com/webpack-contrib/worker-loader plugin.
This with option 
```
// webpack.config.js
{
  loader: 'worker-loader'
  options: { inline: true, fallback: false }
}
```
worked fine for me

**Comment by shershen08** [comment]
also #2 seems related

**Comment by junoprima** [comment]
> 
> 
> If you're using webpack as a build tool you might use https://github.com/webpack-contrib/worker-loader plugin.
> This with option
> 
> ```
> // webpack.config.js
> {
>   loader: 'worker-loader'
>   options: { inline: true, fallback: false }
> }
> ```
> 
> worked fine for me

i dont understand this how can config it i read a lot not clear

**Comment by danimoh** [comment]
Hello.
Thank you for your feedback.
The path is not intended to be hard coded.
It can be adapted via `QrScanner.WORKER_PATH`.
However, the readme was missing documentation on that which I added now.

Also, I added instructions on how to bundle with webpack file-loader.
While not tested, I guess it's also possible to use worker-loader as follows:

```js
import QrWorker from 'worker-loader!./node_modules/qr-scanner/qr-scanner-worker.min.js';
import QrScanner from './node_modules/qr-scanner/qr-scanner.min.js';

const originalWorkerConstructor = Worker;
window.Worker = QrWorker;
const qrScanner = new QrScanner(videoElem);
window.Worker = originalWorkerConstructor;
```

That's not really a nice setup though.
Also the worker loader inlines the worker code as base64, which results in 33% more data and disables parallel download.
I'd suggest to use file-loader as outlined in the readme.

**Comment by NateZimmer** [comment]
From the readme i'm attempting the following via web pack: 

```
import QrScanner from 'qr-scanner'; 
import QrScannerWorkerPath from '!file-loader!./node_modules/qr-scanner/qr-scanner-worker.min.js';
QrScanner.WORKER_PATH = QrScannerWorkerPath;
```

However I get: 
```
Module not found: Error: Can't resolve './node_modules/qr-scanner/qr-scanner-worker.min.js'
```

Do you have to setup webpack somehow in order for this to work?

**Comment by zacharytyhacz** [comment]
> I agree i'd be awesome if this is something that could be brought in with simply `require` like the majority of other node modules out there. Still struggling to get this to work well with web-pack.

I agree, I'm trying to get this to work with Vue + Nuxtjs in dev AND production and still no luck getting it to work.

**Comment by mor12** [comment]
im having problems with IONIC 4 and this plugins, :C any solution ?
