### ISSUE TITLE
Not responsive on smaller screens

### ISSUE THREAD

**Issue by michael-arawole** [nimiq/qr-scanner#161]
The scanner is not responsive on mobile / smaller screens
Tried setting the width of the video elements but it just ruins the scan region

**Comment by onuh** [comment]
If this can be fixed, that's all I need. I tried setting it up too, everything messed up

**Comment by onuh** [comment]
https://smartchurchattendance.com.ng/smartChurch/downloads/Smart_Church_Mobile_1_2.0.apk

**Comment by onuh** [comment]
Use JavaScript to get window screen dimensions and manipulate

**Comment by onuh** [comment]
I use the below code to always set video Hight and width on document ready for my app.

var device_height = window.screen.height + 50;
var device_width = window.screen.width + 50;

// set height and width of video
document.getElementById('qr-video').style.width = device_width+'px';
document.getElementById('qr-video').style.height = device_height+'px';

**Comment by michael-arawole** [comment]
And it worked?

**Comment by onuh** [comment]
Yes

**Comment by onuh** [comment]
You can check the app out

**Comment by michael-arawole** [comment]
Worked 
Thank you 💪🏾
