### ISSUE TITLE
[Question] Is there any way to access the camera stream over HTTP?

### ISSUE THREAD

**Issue by SushiInYourFace** [nimiq/qr-scanner#162]
Hi,

I'm using this application for a small-scale project that will soley be run over the local network. It's somewhat impractical for me to set up certificates to be able to transfer everything over HTTPS, and in general would be slight overkill for the scope of the project. Is there any possible way for me to scan a code using the camera stream if the page is served over HTTP (non-secure)?

**Comment by sisou** [comment]
Browsers can only access device cameras in secure contexts. That means HTTPS or localhost:
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

The only other option is to scan photos that the user took outside the browser, loaded via a file picker input.
