### ISSUE TITLE
is there an npm package?

### ISSUE THREAD

**Issue by NullVoxPopuli** [nimiq/qr-scanner#2]
couldn't find anything on the readme about using this in a project other than just... downloading the files myself

**Comment by domdewom** [comment]
is it possible to create an npm package? How?

**Comment by NullVoxPopuli** [comment]
@domdewom 

so far, I've done this:

```bash
yarn add github:nimiq/qr-scanner
```

```js
// ember-cli-build.js
  // qrcode scanner
  app.import('node_modules/qr-scanner/qr-scanner.min.js', {
    using: [{ transformation: 'es6', as: 'qr-scanner' }]
  });

  // qr-scanner hardcoded this path.... -.-
  var qrScannerWorker = new Funnel(
    'node_modules/qr-scanner/', {
      include: ['qr-scanner-worker.min.js'],
      destDir: '/libraries/qr-scanner/'
    }
  );

// ..
return mergeTrees([
    app.toTree(),
    qrScannerWorker
  ]);
```
https://gitlab.com/NullVoxPopuli/emberclear/blob/master/packages/frontend/ember-cli-build.js



I think maybe because the WebWorker needs to be deployed to `/libraries/qr-scanner/qr-scanner-worker.min.js` that that is why `qr-scanner` isn't an npm package? because it needs deployment configuration

**Comment by andrewebdev** [comment]
I agree, a npm package would be good. Bower is slowly being phased out in many projects, and people are opting for just using NPM and/or Yarn to install packages. We have a project for which _all_ third party libs are installed via NPM, this is the only package we need to manually download and add to the project.

**Comment by danimoh** [comment]
Hello.
It's an npm package now :)
I also added documentation on how to configure the worker path.
