### ISSUE TITLE
Uncaught (in promise) Camera not found.

### ISSUE THREAD

**Issue by Dharit** [nimiq/qr-scanner#20]
Facing issue like this it was showing wrong path for qr-scanner-worker.min.js also faced some other issue solved them but not able to solve this one. If anyone here have solution for this please guide me.

**Comment by gmiller-in-situ** [comment]
I had a similar issue in my first implementation. The issue is that scanner.start() returns a promise which can be rejected if the camera cannot be accessed. You need to handle that rejection like so:
```javascript
this.scanner.start().then(
    () => {
        this.hasCamera = true;
    },
    (error) => {
        console.log(error);
        this.hasCamera = false;
    }
);

**Comment by danimoh** [comment]
Exactly as @gmiller-in-situ says :+1:
