### ISSUE TITLE
Native BarcodeDetector API performance is bad

### ISSUE THREAD

**Issue by jvhellemond** [nimiq/qr-scanner#237]
☝️ This is more of a tip than an issue:

The performance of the native BarcodeDetector API<sup>&thinsp;1</sup> can be pretty bad<sup>&thinsp;2</sup>, causing animations while scanning to be very choppy. Reducing the maximum number of scans per second helps, a bit. Disabling (or removing) window.BarcodeDetector (before calling `.start()`) makes QrScanner load the worker script and do its detecting there:

```js
delete window.BarcodeDetector;
```

<sup>1</sup>: Chrome on non-M1/M2 macOS or Chrome OS or Android only, [for now](https://caniuse.com/mdn-api_barcodedetector)
<sup>2</sup>: In Chrome on my non-M1/M2 Macbook Pro at least, #YMMV

**Comment by DonkeyBear** [comment]
Thanks bro, this tip saves my ass 🥹
