### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by scrim19** [nimiq/qr-scanner#25]
Hi,
I'm currently searching for a way to include a qr-scanning plugin in my webapp project. I need access to the mobile phone's camera and the output should be the string / url of the qr-code.
I found your project and tried to include it like described before. However, I get the following error message:

Uncaught DOMException: Failed to construct 'Worker': Script at 'https://nimiq.github.io/qr-scanner/qr-scanner-worker.min.js' cannot be accessed from origin '// my page reference //'.
    at new QrScanner (https://nimiq.github.io/qr-scanner/qr-scanner.min.js:2:334)
    at // my page reference

Interestingly, I only get the value true or false for the camera existence when referring to your repository but not when referring to my javascripts folder.

Our current architecture is:
- project_folder
    --> index.html
- javascripts
   --> qr-scanner.min.js
   --> qr-scanner-worker.min.js

Did I miss something by chance? I would be really grateful for some replies. Thank you very much and have a nice day!

**Comment by danimoh** [comment]
Hello.
It appears to me, that you're trying to include the worker script directly from `https://nimiq.github.io/qr-scanner/qr-scanner-worker.min.js`?
That's probably blocked by the same origin policy.

You should host the `qr-scanner-worker.min.js` on your own web server and then set the worker path accordingly:
```js
QrScanner.WORKER_PATH = '../javascripts/qr-scanner-worker.min.js';
```

That should fix your issue.

By the way, I'll probably still today release a new version that greatly improves performance.
I recommend to update then.

**Comment by danimoh** [comment]
The new version is released.

I'm closing this for now.
Just comment in case you're still having issues.

**Comment by scrim19** [comment]
Hi danimoh,

yeah I didn't define the worker path correctly, but thanks to your response it works just fine.

Thank you very much and I appreciate your work!
