### ISSUE TITLE
Provide an es5 build without modules

### ISSUE THREAD

**Issue by danimoh** [nimiq/qr-scanner#26]

**Comment by atultherajput** [comment]
I have built the project with ES5. https://github.com/atultherajput/qr-scanner/tree/master/dist

**Comment by rozhok** [comment]
How to use it in ES5 then?

**Comment by sshelton76** [comment]
What would even be the use case for ES5 support?

**Comment by netrevisanto** [comment]
@atultherajput Can you explain how you did this?

**Comment by danimoh** [comment]
The project now provides an `umd` build.
