### ISSUE TITLE
memory leak when trying build in a lit-htm project

### ISSUE THREAD

**Issue by davie-robertson** [nimiq/qr-scanner#29]
When I try and build my project with the WORKER_PATH I get  `allocation failure GC in old space requested` error and the build fails.  If I comment out the WORKER_PATH the code compiles without any errors.

The apps appears to run, although I need to serve via SSL, so hence the need to do a build. 

I'm using the polymer project's lit-element and doing a `polymer build --auto-base-path && gulp prpl-server`

The line in my code is:

```
firstUpdated() {
    QrScanner.WORKER_PATH =  '../components/qr-scanner/qr-scanner-worker.min.js';
    const videoElem = this.shadowRoot.getElementById('scanner') 
    const qrScanner = new QrScanner(videoElem, result => console.log('decoded qr code:', result)); 		
  }

**Comment by danimoh** [comment]
Not sure whether this issue is really related to this project.
Were you able to figure this out?

**Comment by davie-robertson** [comment]
I can't remember now; I'll take a look and see what I did in the end.

**Comment by danimoh** [comment]
Thank you :)
