### ISSUE TITLE
Camera is only enable if you are in https

### ISSUE THREAD

**Issue by pedroSoaresll** [nimiq/qr-scanner#31]
I will play this plugin in my localhost but i received that 'The camera stream is only accessible if the page is transferred via https'

Should localhost be start normally?

**Comment by shrpne** [comment]
it depends on the browser:
chrome - yes
safari - no, even localhost should be served over https

**Comment by pedroSoaresll** [comment]
I did my own lib to show camera linked with qrcode reader.
:)

**Comment by danimoh** [comment]
Generally, the camera is accessible only on sites served via `https`.
`localhost` is an exception to this rule in some browsers.
However, as `localhost` is typically only used during development and not from where the final product will be served, the warning is displayed also on `localhost`, even if the camera is accessible, to make developers aware of the limitation.
