### ISSUE TITLE
does not works in android mobile firefox

### ISSUE THREAD

**Issue by myselfgaurav** [nimiq/qr-scanner#32]
does not works in android mobile firefox, please help with same

**Comment by dasgib** [comment]
Simply set set autoplay attribute of the video-tag: `<video autoplay>`

**Comment by danimoh** [comment]
This issue should not exist anymore in newer versions of Firefox.
Additionally, the video is now also started manually, even if `autoplay` is not set, such that also older Firefox versions should be supported now.
