### ISSUE TITLE
Can't seem to get this working in Angular

### ISSUE THREAD

**Issue by arisnow** [nimiq/qr-scanner#36]
Hi there.  I'm keen to give this a try but I can't seem to get this working in Angular.  Following the instructions I'm simply placing the two javascript files in a folder in Angular, then importing the first one in a component using the statement provided.  For some reason I keep getting a 404 error on finding the worker file.  I tried with the min versions first and am now trying with the non-min versions.  Here's the code...
`import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import QrScanner from 'src/assets/qr-scanner.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  @ViewChild('videoelement') videoelement: ElementRef;
  ngOnInit() {
    this.showVideo();
  }

  showVideo() {
    const qrScanner = new QrScanner(this.videoelement.nativeElement, result =>
      console.log('decoded qr code:', result)
    );
  }
}`

Here's the change I made in the qr-scanner.js file...
QrScanner.WORKER_PATH = 'worker.js';

I've played with different paths but can't seem to get it to work.  I'm sure I'm doing something wrong but any advice would be helpful.

**Comment by kimdah3** [comment]
I got it working this way, maybe it can help.

`import { Component, OnInit, ViewChild } from '@angular/core';
import QrScanner from 'qr-scanner';
@Component({
  selector: 'app-scanner-qr',
  templateUrl: './scanner-qr.component.html',
  styles: []
})
export class ScannerQrComponent implements OnInit {
  @ViewChild('video')
  videoElem: any;
  result: any;

  constructor(private scannerService: ScannerService) {}

  ngOnInit() {
    QrScanner.WORKER_PATH = './assets/qr-scanner-worker.min.js';
    const qrScanner = new QrScanner(this.videoElem.nativeElement, result => {
      this.result = result;
    });
    qrScanner.start();
  }
}`

**Comment by danimoh** [comment]
@kimdah3 's code looks good :+1:
Note that the `WORKER_PATH` needs to be set before creating the `QrScanner` instance.
