### ISSUE TITLE
Not working only on iPhone

### ISSUE THREAD

**Issue by Cyber-code** [nimiq/qr-scanner#37]
I have this error only with iPhone :
"NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."

But I accept that camera can be used.
It's very strange because on iPad it's work perfectly.

**Comment by AmirSasson** [comment]
@Cyber-code i also having difficulties in iphone.
did you manage to solve them?

**Comment by Cyber-code** [comment]
I didn't solve them, i'm use to launch app on android or on iPad for the moment. 

It's very strange because on the website demo, on iPhone it's ok. I tried to use the same code and still have the same error.

**Comment by ekocahyonugroho** [comment]
You need to run in https mode . iPhone more strict on this

**Comment by almat83** [comment]
try to add "muted" and "playsinline" attributes to <video> tag

**Comment by danimoh** [comment]
Yes, `muted` and `playsinline` had to be set on the video.
These are now set automatically.
Please open a new issue if you're still experiencing this problem.
