### ISSUE TITLE
Need to export QrScanner properly and need to call .start()

### ISSUE THREAD

**Issue by sshelton76** [nimiq/qr-scanner#39]
Just a suggestion, but you may wish to include something like.
When ready to open the QR scanner, be sure to call
```
QrScanner.start();
```

I had to follow the code to find that.  It might be obvious to you, but technically it's undocumented.
Also the minified version isn't exporting QrScanner.  It exports "e".  You should check whatever you've got munging your build and ensure it preserves the class name.

Other than that, Great work!

**Comment by mistermashu** [comment]
omg that's why it wasn't working at all! Definitely need to add `start()` to the docs.

**Comment by danimoh** [comment]
This is now included in the documentation.

Yes, the class name gets minified, but as it gets exported as default export (i.e. not named export) and can be imported as any name, I don't think there is a problem?
