### ISSUE TITLE
Cannot decode image

### ISSUE THREAD

**Issue by fschai89** [nimiq/qr-scanner#4]
When I upload the original QR Code image file, it cannot be decoded, however if I take the qr code image with camera and upload, it work. Wonder why?

Image that not work
![qr-code](https://user-images.githubusercontent.com/12872679/43053820-47a0323e-8e61-11e8-8bbc-a51ddd011095.jpg)

Image that work:
![20180719_093137 copy](https://user-images.githubusercontent.com/12872679/43053838-5eb99af0-8e61-11e8-9ea3-93f1e2da3b4c.jpg)
![20180719_093137](https://user-images.githubusercontent.com/12872679/43053839-5ee4fe02-8e61-11e8-937d-e1e83b767c3e.jpg)
![20180720_180930 copy](https://user-images.githubusercontent.com/12872679/43053840-5f3ad6d8-8e61-11e8-8db9-902f47834387.jpg)

**Comment by danimoh** [comment]
Hello.
The library is regularly improving and this seems to be working now :+1:.
In case it is still not working for you, you might want to experiment with the canvas size setting.
