### ISSUE TITLE
Time gap between success reads of qr code, cause it scans to fast.

### ISSUE THREAD

**Issue by masterdany88** [nimiq/qr-scanner#44]
QRcodes are to scanned to many times. If it scanned once, it should have been some timeout to somehow proceed scanned code.

**Comment by willypt** [comment]
You can wrap the `onDecode` function using `debounce`.

```
    const qrScanner = new QrScanner(
      videoRef.current,
      debounce(async result => {
        console.log('decoded qr code:', result);

        qrScanner.stop();
        setLoading(true);

        const [decodeResult, err] = await new Promise(resolve => resolve([true, null]));

        console.log({ decodeResult, err });

        if (decodeResult) {
          console.log('Do action');
          qrScanner.destroy();
        } else {
          qrScanner.start();
          setLoading(false);
        }
      }, 300),
    );

    qrScanner.start();
```

**Comment by masterdany88** [comment]
Did You tested?

**Comment by danimoh** [comment]
The scanner does not process multiple frames at once.
The next frame is processed just after the previous frame finished processing.
If you do not want to receive further scan results after a successful scan, you can simply `stop()` the scanner after a successful scan.
Alternatively, you can adapt your `onDecode` callback to ignore subsequent successful scans after the first one.
