### ISSUE TITLE
Call QR scanner in a function

### ISSUE THREAD

**Issue by WeiYWei** [nimiq/qr-scanner#46]
Hi danimoh,
first I would like to appreciate your module. I have been trying your qr scanner. I could successfully include your qr scanner and it basically worked fine.
However, at the moment the camera is active the whole time. Precisely, the camera is active immediately after the html-page has been loaded and it remains active even after the qr scanner has successfully detected a qr-code. This is the only possibility at the moment for me to make the qr-scanner work.

In your usage description, I found code for starting and destroying the qr scanner instance.
Therefore, I tried to include the code scanner.start() in one of my functions. 
These functions are only used after the user has fired an event through user input.
My javascript functions are loaded from a seperated file by the tag
<script type="text/javascript" src="my.js"></script>

The qr-script however is embedded in a <script type="module"></script> tag.
I assume that the different attribute of the script-tags is the problem.

Is there any possibility to use the scanner.start() function in my own functions?
Where can I use the scanner.destroy() function?

I would be grateful if you have a solution for my problem.

Kind Regards
WeiYWei

**Comment by willypt** [comment]
You may try including `qrscanner` variable on the `window` scope and try calling it from there.

**Comment by danimoh** [comment]
You can also load the scanner in non-module code via a dynamic import: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports

**Comment by danimoh** [comment]
The library is additionally now provided as `umd` version.
Instructions for importing this library from non-module scripts have been added tot the readme.
