### ISSUE TITLE
Scanner error: timeout

### ISSUE THREAD

**Issue by willypt** [nimiq/qr-scanner#47]
I keep getting Scanner error: timeout

```

(anonymous) | @ | index.js:3714
-- | -- | --
  | (anonymous) | @ | qr-scanner.js:217
  | Promise.then (async) |   |  
  | (anonymous) | @ | qr-scanner.js:214
  | sentryWrapped | @ | index.js:3212
  | requestAnimationFrame (async) |   |  
  | (anonymous) | @ | index.js:3457
  | _scanFrame | @ | qr-scanner.js:213
  | _onPlay | @ | qr-scanner.js:191
  | (anonymous) | @ | 6LBW8-H9LPR-9M23M-JHQ3F-U5FUY:16
  | sentryWrapped | @ | index.js:3212
  | play (async) |   |  
  | _onCanPlay | @ | qr-scanner.js:186
  | (anonymous) | @ | 6LBW8-H9LPR-9M23M-JHQ3F-U5FUY:16
  | sentryWrapped | @ | index.js:3212


```

There's no additional info. Can someone help me?

**Comment by KingRial** [comment]
I'm having the same issue; I will keep you updated if I find anything

**Comment by willypt** [comment]
Hi, this happens because the worker file is not loaded correctly. @KingRial hope you resolved this issue already

**Comment by hrmdbipolar** [comment]
> I keep getting Scanner error: timeout
> 
> ```
> 
> (anonymous) | @ | index.js:3714
> -- | -- | --
>   | (anonymous) | @ | qr-scanner.js:217
>   | Promise.then (async) |   |  
>   | (anonymous) | @ | qr-scanner.js:214
>   | sentryWrapped | @ | index.js:3212
>   | requestAnimationFrame (async) |   |  
>   | (anonymous) | @ | index.js:3457
>   | _scanFrame | @ | qr-scanner.js:213
>   | _onPlay | @ | qr-scanner.js:191
>   | (anonymous) | @ | 6LBW8-H9LPR-9M23M-JHQ3F-U5FUY:16
>   | sentryWrapped | @ | index.js:3212
>   | play (async) |   |  
>   | _onCanPlay | @ | qr-scanner.js:186
>   | (anonymous) | @ | 6LBW8-H9LPR-9M23M-JHQ3F-U5FUY:16
>   | sentryWrapped | @ | index.js:3212
> ```
> 
> There's no additional info. Can someone help me?

Hello, I have the same problem. If you have solved it, can you please help me ?

**Comment by danimoh** [comment]
Hello @KingRial and @hrmdbipolar,
as @willypt said, configuring the worker file was necessary, for the scanner to work.
However, in the newest versions, this is not necessary anymore and scanning now works out of the box.
