### ISSUE TITLE
Refused to execute script - because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by dale-waterworth** [nimiq/qr-scanner#49]
I'm using Angular 7, works fine on localhost but in production i see the error below. Any ideas how to get around it?

`Refused to execute script from '<domain>/assets/qr-scanner-worker.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

After some digging around i came across this statement but still more idea:

`When you have a script that is not in the head of a document, the javascript it loads is labeled with the wrong mime type ('text/html')`

**Comment by Dabugger** [comment]
got same error, and script is not working.

**Comment by kwongtn** [comment]
You need to change the content type to `text/javascript` for it to work, its kinda like a security feature.
Here's a sample of the code for the loading of js file.
```
fs.readFile("./" + q.pathname, "utf-8", (err, content) => {
            res.writeHead(200, { 'Content-Type': 'text/javascript' });
            res.end(content);
        });
```

**Comment by deviashin** [comment]
> You need to change the content type to `text/javascript` for it to work, its kinda like a security feature.
> Here's a sample of the code for the loading of js file.
> 
> ```
> fs.readFile("./" + q.pathname, "utf-8", (err, content) => {
>             res.writeHead(200, { 'Content-Type': 'text/javascript' });
>             res.end(content);
>         });
> ```

Hi, please tell me what to do with the code that you showed, where to put it so that there is no security check (I have a local application for myself)

**Comment by danimoh** [comment]
You need to configure your server to serve the worker file with the correct mime type.
As this is not a problem of the lib itself, I'm closing this issue.
