### ISSUE TITLE
Doesn't Detect QR Code

### ISSUE THREAD

**Issue by bm2112** [nimiq/qr-scanner#5]
I've used the exact clone of the repository in my ASP.NET project and it fails to recognize any QR Codes. I also uploaded to an IIS server to see if it was an issue with debugging in Visual Studio, but it still doesn't recognize QR Codes. The demo however, works on all of my devices, so I do not understand why an exact clone would not work.

**Comment by MatheusRich** [comment]
Up

**Comment by Gabrui** [comment]
You must include a file in the public folder: /libraries/qr-scanner/qr-scanner-worker.min.js
Besides the qr-scanner.min.js in your public folder

**Comment by danimoh** [comment]
As the Readme includes more extensive instructions for already some time now and there were no further details about any potential other issue, I'm closing this.
