### ISSUE TITLE
How can i use this scripts in php file ? 

### ISSUE THREAD

**Issue by Govind13100** [nimiq/qr-scanner#50]
Hi there, 

My project is in PHP language and I need a QR code scanner by enabling the webcam or mobile camera. 

I have used your scripts and created a new object using the following code in .php file  
```
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script type="text/javascript" src="<?php echo get_site_url(); ?>/wp-content/themes/north-shore-child/qr-scanner.min.js"></script>
	<script type="text/javascript" src="<?php echo get_site_url(); ?>/wp-content/themes/north-shore-child/qr-scanner-worker.min.js"></script>
</head>
<body>
	<video></video>

	<script type="text/javascript">
		const qrScanner = new QrScanner(videoElem, result => console.log('decoded qr code:', result));
	</script>
</body>
</html>
```

But it throws an error : 

![Screenshot 2019-07-06 at 1 04 47 PM](https://user-images.githubusercontent.com/26818036/60753372-e4baf000-9fee-11e9-9330-bc63f1eb3c46.png)

Can anyone help me here?

**Comment by Drivez** [comment]
Any luck with this?

**Comment by bigz3ro** [comment]
I have same error.

**Comment by danimoh** [comment]
Hello.
Please have a look at the readme.
This lib is a es6 module which needs to be imported accordingly by a native import from within an es6 module.
However, an `umd` build has been added now, which can be used as a normal script.
