### ISSUE TITLE
Unsupported image type when passing in a blob (JPEG, PNG), works with img with the same src

### ISSUE THREAD

**Issue by TomasHubelbauer** [nimiq/qr-scanner#52]
I am trying this library out and I've noticed that despite the following URL saying you can pass in a blob, it doesn't work:

https://github.com/nimiq/qr-scanner#single-image-scanning

My blobs, created using `fetch` have proper MIME types, but the library rejects them with *Unsupported image type*. When taking the same URL, placing it in an `img src` and passing that in, the library successfully decodes it.

**Comment by danimoh** [comment]
Indeed, thank you for reporting.
This is fixed now.

**Comment by TomasHubelbauer** [comment]
Great work, thanks for implementing this!
