### ISSUE TITLE
update webpack readme setup + missing usage code

### ISSUE THREAD

**Issue by poolerMF** [nimiq/qr-scanner#53]
in setup it says to use 
````
import QrScannerWorkerPath from '!!file-loader!./node_modules/qr-scanner/qr-scanner-worker.min.js';
````

but it's not working for me ... it works only when:
````
import QrScannerWorker from '!!file-loader!qr-scanner/qr-scanner-worker.min.js';
````

**in Usage, there should be included this code:**
````
qrScanner.start();
````

**Comment by kpjf** [comment]
@poolerMF, thank you. I was doing the same, and didn't have that the call to `start`.

**Comment by gushonorato** [comment]
I've sent a pull request fixing the docs

https://github.com/nimiq/qr-scanner/pull/60

@nimiq can you please merge it?

**Comment by danimoh** [comment]
Thanks for all suggestions. These are now part of the readme.
