### ISSUE TITLE
Stop scanning for a while

### ISSUE THREAD

**Issue by hamoha31** [nimiq/qr-scanner#55]
Hi,

How to stop the scanning process until I request it to come back again. 

I destroyed the object then recreate it, but it never works.

Is there anyway to do it?

**Comment by Drivez** [comment]
This is one example 
```
<script type="module">
	import QrScanner from '/js/qr-scanner.min.js';

	QrScanner.WORKER_PATH = '/js/qr-scanner-worker.min.js';

	const videoElem = document.getElementById('video');
        // When you click a scan button, create the instance
	$('.scanner-btn').on('click', function () {
	const qrScanner = new QrScanner(videoElem, result => {
	
	   $('#search_string').val(result);
	   setTimeout(function () {
		$('#form').submit();
                 // After i submit the code for validation, destroy the instance ( since it uses alot of CPU)
		qrScanner.destroy();
	   }, 100);
	  });
	qrScanner.start();
	})
</script>
```

**Comment by Nakilon** [comment]
I wonder if it's possible to read webcam data with lower fps.

**Comment by danimoh** [comment]
Hello.
The scanner provides a `stop` method which can be used for stopping the web cam scanning.
It can then later be resumed by calling `start` again.

`destroy` is not an appropriate way to pause ad later resume the scanning as it completely destroys and cleans up a scanner instance.
Documentation for `stop` has now been added to the readme.

@Nakilon 
Throttling the fps is currently not supported.
The scanner tries to scan qr codes as quickly and snappy as possible.
However, you could indeed throttle the scanning yourself by using `stop` and `start` after each scan attempt in `onDecode` and `onDecodeError` callbacks.
