### ISSUE TITLE
Camera not showing

### ISSUE THREAD

**Issue by Xayah29** [nimiq/qr-scanner#57]
No cameras detected/showing when i run my system locally.

**Comment by zspitzer** [comment]
Is this in Firefox? 

it works in nightly, but the camera icon doesn't turn off when you destroy the scanner  (see https://bugzilla.mozilla.org/show_bug.cgi?id=1192170 )

**Comment by danimoh** [comment]
As no further details have been provided here, I'm closing this.
As @zspitzer said, the page has to be served via `https`.
