### ISSUE TITLE
iOS Chrome

### ISSUE THREAD

**Issue by akbarnoor94** [nimiq/qr-scanner#58]
The Qr Scanner does not work in ios google chrome. Does anyone know how to solve it?
I've already put the muted and playsinline in the video tag. It works perfect in android chrome and ios safari. Also I've already use https

**Comment by akbarnoor94** [comment]
Is there anyone can help me?

**Comment by KingPin** [comment]
afaik ios doesnt allow access to camera stream on any browser other than safari. chrome/firefox etc on ios are just webkit reskins.

**Comment by akbarnoor94** [comment]
@KingPin thanks mate
