### ISSUE TITLE
No callback to setResult when using safari in iOS 13 

### ISSUE THREAD

**Issue by ymh2** [nimiq/qr-scanner#61]
The code work properly on firefox in macbook/android, chrome in android and safari below iOS 12.  But it is not working in iOS 13 ( camera shown but never call setResult ) . Any advance on this problem?

**Comment by andrewbee** [comment]
I am also experiencing this problem. All is fine on Chrome and IE on my pc and is ok on my android chrome but anything  iOS related seems to stop after first frame is rendered to video.
Is there anything I can do to rectify this or is the component not iOS compatible?

**Comment by callumgarven** [comment]
I am also experiencing this issue with IOS 13.1.3, on a 5th gen iPad - not detecting any QR Codes

**Comment by akondo06** [comment]
anyone has any idea? It also gets stuck on first frame for me.

**Comment by akondo06** [comment]
@ymh2 not sure if this is a fix for you .. but have you tried adding the `autoplay` and `playsinline` attributes on the video element? (taken from the demo). That fixed my issues on iOS 12 and 13.

**Comment by SamWarmuth** [comment]
Has anyone had any success fixing this? Using `muted` and `playsinline`allows the video feed to show, but `setResult` is never called. It works fine on various other devices.

**Comment by andrewbee** [comment]
We built a URL into the QR code and sent the information using a query
string in the end because of the ios problem. If you do this you can then
pass the QR code reading back to the devices native QR reading function but
still have an information received response on your website.

Feel free to set up a zoom meeting with me or similar if you would like
more explanation... its not like I'm doing anything else at the moment
after my work  due to lockdown.

Andrew Blackburn

Sent from my clunky old desktop

Mobile: 07970 019818
Land: 01291 622661

**Comment by SamWarmuth** [comment]
I ended up switching to https://github.com/JodusNodus/react-qr-reader , which works flawlessly on iOS. Still not sure what the issue was with this library.

**Comment by danimoh** [comment]
Hello.
Recent changes should potentially have fixed this.
Can you please test again?

**Comment by ferdinandfrank** [comment]
Hi, I'm still having the same issue on iOS 14. The video is being displayed but no result is called.

I'm also receiving the following error on our error monitoring tool:
`SecurityError: The operation is insecure.`

Sadly, no further information, e.g., a stack trace, is provided.
Anyone had success with the scanner on iOS?

**Comment by tmirun** [comment]
@ferdinandfrank check if you are in **https**

**Comment by danimoh** [comment]
Some Safari specific fixes have been added in the meantime.
Is any of you still experiencing issues in Safari?

**Comment by danimoh** [comment]
I believe these issues were fixed by the July 2020 changes as no further comments were posted anymore.
On an iPhone I tested on, it works just fine.
If you still encounter issues, feel free to open a new issue.
