### ISSUE TITLE
"QR Code not found" if image size is to big (2MB)?

### ISSUE THREAD

**Issue by U056583** [nimiq/qr-scanner#62]
I have testet the function "Scan form file:" in demo https://nimiq.github.io/qr-scanner/demo/ with the same image in two different sizes (61 KB, 1500 kb) on a iPhone and WIN10-PC.
 
With the size 61 KB (and 360kb as well): QR Code was proberly detected
With the size 1500 KB: QR Code was not detectet. "Detected QR code: QR code not found."

Question: Is there a size limit to the Image/file? 
How can get around that Problem?

Any help would be great!
Thomas
Attachment: the 2 files/Images 
![IMG_4417-61KB](https://user-images.githubusercontent.com/46089144/71770493-5091fd00-2f2d-11ea-8e2d-c93398f080d0.JPG)
![IMG_4417-2000KB](https://user-images.githubusercontent.com/46089144/71770494-512a9380-2f2d-11ea-9fe7-2a67a4b00f69.JPG)

**Comment by danimoh** [comment]
Hello Thomas.
Thank you for these test images.
I also noticed that the scanner seems to struggle with very big images. Unfortunately, I didn't find the time yet to investigate this.
You can work around this by drawing the image to a smaller canvas though. The following works for me for both images:
```js
const canvas = document.createElement('canvas');
canvas.width = 480;
canvas.height = 640;
QrScanner.scanImage(file, null, null, canvas, true);
```
Note that the canvas should have the same aspect ratio as the image.

**Comment by danimoh** [comment]
Down scaling to a custom size is now supported more elegantly, see readme.

**Comment by U056583** [comment]
Thank You so much for fixing the problem!
