### ISSUE TITLE
Return location of detected code

### ISSUE THREAD

**Issue by suzukieng** [nimiq/qr-scanner#66]
It would be useful to return the location of the detected code in the image (coordinates of corners), for augmented reality applications.

**Comment by danimoh** [comment]
Will be added in the future, cf. https://github.com/nimiq/qr-scanner/issues/109

**Comment by danimoh** [comment]
This is now supported :)
You can now get both, the coordinates of the corners and the outline of the code rendered on screen.
Have a look at the readme.
