### ISSUE TITLE
Safari:  Array size is not a small enough positive integer.

### ISSUE THREAD

**Issue by zspitzer** [nimiq/qr-scanner#71]
```
name: RangeError
message: Array size is not a small enough positive integer.
stack: qr-scanner-worker.min.js (24,158)
```

This was previously working on iOS, but Safari 13 / Webkit seems to have a regression, so I have filed a bug against webkit.

https://bugs.webkit.org/show_bug.cgi?id=211619

The error is happening the jsQR library
https://github.com/cozmo/jsQR/issues/157

**Comment by danimoh** [comment]
Hello @zspitzer.
I indeed believe it's a bug in Safari.
Thank you for opening the webkit bug.

In the latest version I applied a workaround that hopefully mitigates this issue.
Please test it and report any issues in https://github.com/nimiq/qr-scanner/issues/102.
