### ISSUE TITLE
Allow Camera Access Permissions

### ISSUE THREAD

**Issue by fjerrichiello** [nimiq/qr-scanner#73]
I'm having some trouble with when the camera page pops up. It currently just shows up and doesn't ask the user for permissions. Then the camera won't show up. How would I make it prompt the user for permissions?

**Comment by danimoh** [comment]
So the video on https://nimiq.github.io/qr-scanner/demo remains black for you / doesn't show at all?
But no permission prompt gets opened?
What Browser and Operating System are you using?

**Comment by FurtunaDaniel** [comment]
Hey @danimoh ,
I checked on Opera and Chrome (Android).
On Opera, it appears in the pop-up but Chrome goes on the back camera without asking.
