### ISSUE TITLE
More documentation needed

### ISSUE THREAD

**Issue by Sjeiti** [nimiq/qr-scanner#75]
I am struggling with what is described in the readme and what is actually exposed on the class and instance.

At first I was trying to `pause` the scanner but it detaches the stream from the video. Is that intentional? (imho it should not be since it didn't attach it in the first place).
Then I noticed that on the prototype there is `start`, `stop` , `pause` and `destroy`. How do these methods compare?

There is also the static `DEFAULT_CANVAS_SIZE` and `hasCamera` that are undocumented.

**Comment by danimoh** [comment]
Thanks. I improved the documentation.
And yes, `pause` / `stop` is the counterpart which attaches the camera stream to the video, so stopping it on `pause`/`stop` is intentional.

**Comment by Anhaachan** [comment]
why this issue is closed when didn't answer `DEFAULT_CANVAS_SIZE and hasCamera that are undocumented.` here
