### ISSUE TITLE
mirroring video set by inline style

### ISSUE THREAD

**Issue by Sjeiti** [nimiq/qr-scanner#76]
I was trying to center a video with the old CSS combo `margin-left: 50; transform: translateX(-50%);` but qr-scanner code negates that by using inline styling to `transform: scaleX(-1)` (or 1).

The current fix I now use is ugly:

```
video.style.transform = 'translate(-50%, -50%) ' + video.style.transform
```

Wouldn't it be better to toggle a className for mirroring the video? The CSS declarations themselves could easily be done from within JavaScript.

I'd propose a default className of `qr-scanner` and the mirroring done by toggling `qr-scanner--mirror`. This makes implementing other transforms a lot easier.

I'll add a pull request.

**Comment by danimoh** [comment]
See https://github.com/nimiq/qr-scanner/pull/77
