### ISSUE TITLE
It has some problem to build

### ISSUE THREAD

**Issue by shynome** [nimiq/qr-scanner#80]
1. `git clone https://github.com/nimiq/qr-scanner.git`
1. `npm install`
1. `npm run build` then throw error:
    ```log
    > rollup --config

    [!] Error: Cannot find module 'acorn'
    ```

**Comment by sowmyaramalingam** [comment]
can u build using visual studio .. i did using visual studio.. i hosted it..but its damn slow

**Comment by shynome** [comment]
@sowmyaramalingam sorry I can't, I don't have visual studio
Can you build successful by visual studio?

**Comment by sowmyaramalingam** [comment]
YES I DID,,,  use this comment to view error message 

rm -rf node_modules
npm install

**Comment by sowmyaramalingam** [comment]
did u install node modules perfectly  in project directory ?

**Comment by shynome** [comment]
no perfect, there are some warn:
```log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-osx@^20181125.0.1 (node_modules/@ampproject/rollup-plugin-closure-compiler/node_modules/google-closure-compiler/node_modules/google-closure-compiler-osx):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-osx@20181125.0.1: wanted {"os":"darwin","arch":"x64,x86"} (current: {"os":"linux","arch":"x64"})
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
```
and I have tried run `npm ci` this cammand install pacakge follow package-lock.json and it throw errors:
```log
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Missing: @ampproject/rollup-plugin-closure-compiler@^0.8.5
npm ERR! Missing: jsqr-es6@^1.2.0-2
npm ERR! Missing: rollup@^1.1.2
npm ERR! Missing: rollup-plugin-sourcemaps@^0.4.2
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2020-07-08T15_44_02_752Z-debug.log
```
if I install `rollup` firstly, everything will be ok, it seem is rollup version is too old in package.json
```sh
git clone https://github.com/nimiq/qr-scanner.git
cd qr-scanner
npm i rollup
npm i
npm run build
```

**Comment by sowmyaramalingam** [comment]
mail ur code sowmyaramalingm@gmail.com

**Comment by sowmyaramalingam** [comment]
https://stackoverflow.com/questions/45287398/is-there-a-way-to-confirm-a-package-lock-json-actually-resolves-all-dependencies

**Comment by shynome** [comment]
I don't know the mean of the link, my question is this repo package-lock-json is broken, it doesn't lock packages, it missed some package which should be installed and record in package-lock.json
just need update `rollup` and use the `npm install` command to update `package-lock.json` can fix this build error

**Comment by shynome** [comment]
finally I found it just is `@ampproject/rollup-plugin-closure-compiler` is not apear in `package-lock.json`, so `npm i` doesn't install it, then `npm run build` failed

**Comment by sowmyaramalingam** [comment]
use this https://github.com/cozmo/jsQR

**Comment by sowmyaramalingam** [comment]
its much better than this one

**Comment by shynome** [comment]
Thanks you for replay

**Comment by sowmyaramalingam** [comment]
you try jsqr its very faster than nimiq

**Comment by danimoh** [comment]
@sowmyaramalingam 
This library is based on jsQR. However, it includes several improvements:
- it supports web cam scanning out of the box
- it uses a web-worker to not block the main thread
- several performance improvements have been applied. Here is a benchmark: https://github.com/danimoh/qr-scanner-benchmark (where cozmo in the test results is the original jsQR lib and cozmo2 the improved version used here).
- reduced memory footprint
- lightweight
