### ISSUE TITLE
Highlight the scan region

### ISSUE THREAD

**Issue by max2ti** [nimiq/qr-scanner#86]
As far as I understand, using the camera, only a square (configurable size) at the center of the image is processed. I think it would be nice to have it highlighted to make things easier for the users.

Maybe darken the useless area, or draw a red square in the center, something like that.

**Comment by fcsegalla** [comment]
This is working for me:
HTML:
`<div id="divVideo">
   <video id="qr-video" style="width: 100%;"></video>
</div>`

CSS:
`
#divVideo {
  position: relative;
}
#qr-video {
  min-height: 100%;
  min-width: 100%;
  height: auto;
  width: auto;
}
#divVideo:before {
  position: absolute;
  content:"";
  height: 60%;
  width: 60%;
  border: 2px dashed red;
  top: 20%;
  left: 20%;
  z-index: 1;  
}
`

**Comment by MScofied** [comment]
Agree. Any idea of how to do it? or is there any reference that i can refer to, thanks

**Comment by ramclen** [comment]
I think you could actually do it using CSS, they have the function that calculate the square in the code, in that way you could do it manually.

**Comment by danimoh** [comment]
This is now supported by the library :tada: 
The rendered outline can be easily styled via css.
Have a look at the readme and demo for examples.
