### ISSUE TITLE
Not working in Chrome browser

### ISSUE THREAD

**Issue by lwloon** [nimiq/qr-scanner#87]
Both web cam scan and upload QR not working in Chrome.

I've setup local dev and online version https://nimiq.github.io/qr-scanner/demo/ both also return "No QR code found" 

Version 84.0.4147.89 (Official Build) (64-bit)

Tested in safari it is working as expected.

**Comment by sisou** [comment]
I'm guessing you are talking about MacOS? Or iOS?

**Comment by photo-art-melanie-frei** [comment]
For me the same on iOS.
Are there any known limitation with regards to iOS and chrome?

**Comment by sisou** [comment]
Apple doesn't allow other browsers than Safari to access the cameras on iOS.

So on iOS, only Safari will work.

**Comment by TLenahan** [comment]
This issue has been resolved on iOS 14.3. Chrome now has access to the camera.
