### ISSUE TITLE
Update package installed from npm

### ISSUE THREAD

**Issue by brunok** [nimiq/qr-scanner#88]
The code version installed with **npm i qr-scanner** ("qr-scanner": "^1.2.0") is not corresponding to the code on github and, more important, to the documentation (e.g. the parameters for the constructor). Please correct as this is quite disturbing... 😉

Greetz and thanks for a great product

**Comment by Robin-Hoodie** [comment]
Just ran into this too. Quite confusing as the option to provide a custom scanning region has been here since July, but is not actually included in the version that's distributed on NPM

**Comment by danimoh** [comment]
Thanks.
A new version has been published now, with a couple of additional improvements :)
