### ISSUE TITLE
Can not detect camera on laptop and mobile

### ISSUE THREAD

**Issue by courtney1403** [nimiq/qr-scanner#94]
I download your zip files and run local.
It works well with all-in-one computer, but can not detect camera on laptop and mobile.
I don't know where the issue is. Please help me.

**Comment by courtney1403** [comment]
Actually, I checked more carefully.
I worked on laptop. But:
1. When I make my laptop as a local server and run => it's OK.
2. But when I access the page from another computer in the LAN, it said: **Device has camera: false.**
(I used XAMPP as web server).

**Comment by sisou** [comment]
Hi @courtney1403,

The camera is only accessible to websites served over HTTPS and to localhost. So if you access your server from another device via an unsecured HTTP IP address, it won't work. 

You can try to use routing services like ngrok (https://ngrok.com) to access your local test site from an other device via HTTPS.

Let me know of that helps.

**Comment by courtney1403** [comment]
Thank you so much.
I changed the server to https and it worked like charm. :)

**Comment by sisou** [comment]
Great! Happy coding! 😊👍
