### ISSUE TITLE
error, when scanning image with one color

### ISSUE THREAD

**Issue by poolerMF** [nimiq/qr-scanner#96]
when I put camera to image, that cointains of one color (for exmaple black), than error occured while scanning

in console I am just getting error without message
It says message = null, error on line 653, column 66
![error_scanning](https://user-images.githubusercontent.com/4276289/93665515-4ee67600-fa77-11ea-844c-9f2a8ed14625.PNG)

**Comment by danimoh** [comment]
Seems to be the same as https://github.com/nimiq/qr-scanner/issues/102.
It's not related to the QR code color but rather seems to be a Safari internal bug.
I implemented a fix to circumvent this.
Please test it and report whether it worked for you in #102.
