### ISSUE TITLE
iOS 14.1 can't scan with hidden video

### ISSUE THREAD

**Issue by Eschon** [nimiq/qr-scanner#97]
Not sure if you can even do anything about it but I found an interesting behaviour that just cost me a few hours to figure out, so I thought I'll post it here to maybe help other people that implement the scanner like me.

You can't set display:none on the video element you use for the scanner.

In my Scanner-Application I was just showing the $canvas instead of the full video. I just inserted the canvas and set display:none on the video. Apparently Safari doesn't allow that anymore, I guess the video just stops automatically if display is none. To work aroud it I just moved the video off screen

**Comment by hirakujira** [comment]
You can also set video height and width to 0px

**Comment by danimoh** [comment]
Thanks for reporting.
For improved dev experience, the lib now tries to mitigate this and some other Safari pitfalls automatically :)
See https://github.com/nimiq/qr-scanner/commit/d7a09be0880417a63e0cb557ff2addf64d2bd7df
