### ISSUE TITLE
Initialization sometimes fails because native barcode detection is unavailable

### ISSUE THREAD

**Issue by suzukieng** [nimiq/qr-scanner#98]
Observed on Android 10, Galaxy S10+.

Sometimes initializing the QR scanner succeeds, but the library fails to initialize the native barcode detection support (see console output). What the user sees is a green screen (no idea why).

<img width="1234" alt="Screenshot 2020-11-12 at 16 55 25" src="https://user-images.githubusercontent.com/3542048/98963877-6fc3c880-2508-11eb-9d73-4876435f3edb.png">

There should be a way to opt-out of the native barcode detection, even though the platform might support it.

**Comment by syk0saje** [comment]
+1 on this issue, although in my case things initialize just fine, it's just that the native BarcodeDetector cannot handle certain big QR codes that work just fine when using a Worker engine.

**Comment by danimoh** [comment]
Hello, the library now automatically disables the native `BarcodeDetector` if it encounters a "not implemented" or "service unavailable" exception.
The "service unavailable" exception was already handled before by creating a new `BarcodeDetector` instance which usually seemed to recover from the error state. However, I now merged it with the "not implemented" case to then disable the native `BarcodeDetector` altogether as in newer browsers the `BarcodeDetector` crashing with a "service unavailable" error during normal operation does not seem to occur anymore.

@syk0saje if you still have this issue, please open a new issue with more details, e.g. what exactly do you mean by "big"? High QR code version (large amount of data encoded in the QR code) or QR code images of high resolution (large images with a lot of pixels) or the QR code being held close to the camera? Are you scanning from file or from the webcam? Can you post an example QR code that's failing for you?
Until then, you can use `QrScanner._disableBarcodeDetector = true` before creating your QrScanner instance as a hack if you still have this issue.

For now I did not add a public option to disable use of the native `BarcodeDetector` as I plan to instead add a possibility to state an order of preference of scanner engines when I potentially add additional engines.
