### ISSUE TITLE
Fallback facingMode seems unused

### ISSUE THREAD

**Issue by caipirginka** [nimiq/qr-scanner#99]
At line 144 of file "qr-scanner.js", the facingMode is swapped between 'environment' and 'user', if no stream was retrievd for previous value:
`facingMode = facingMode === 'environment' ? 'user' : 'environment';`

But then, at the following line, the new value is not passed to the `_getCameraStream()` function, so the swap was pointless:
`return this._getCameraStream(); // throws if camera is not accessible (e.g. due to not https)`

Line 145 should probably instead read:
`return this._getCameraStream(facingMode, true); // throws if camera is not accessible (e.g. due to not https)`

Isn't it?

**Comment by danimoh** [comment]
Hello @caipirginka.
This is indeed intended.
We try to detect the facingMode to mirror the video accordingly only.
It's not used in the fallback `_getCameraStream` call.
Instead, when the first attempt for the preferred camera failed, we're trying an unconstrained attempt, which then should return the other camera, or at least hopefully anything.
